openapi: 3.0.1
info:
  title: Customer API
  description: API for managing customer data.
  version: 1.0.0
servers:
- url: http://localhost:3000/api
paths:
  /customers:
    get:
      summary: Get all customers
      responses:
        '200':
          description: A list of customers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
    post:
      summary: Create a new customer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerInput'
      responses:
        '201':
          description: Customer created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '400':
          description: Bad request
  /customers/{id}:
    get:
      summary: Get a customer by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A single customer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '404':
          description: Customer not found
    delete:
      summary: Delete a customer by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Customer deleted successfully
        '404':
          description: Customer not found
    patch:
      summary: Update a customer by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerInput'
      responses:
        '200':
          description: Customer updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '400':
          description: Bad request
        '404':
          description: Customer not found
components:
  schemas:
    Customer:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the customer
        firstName:
          type: string
          description: Customer's first name
        lastName:
          type: string
          description: Customer's last name
        phoneNumber:
          type: string
          description: Customer's phone number
        postCode:
          type: string
          description: Customer's postal code
        dateOfBirth:
          type: string
          format: date
          description: Customer's date of birth
      required:
        - id
        - firstName
        - lastName
        - phoneNumber
        - postCode
        - dateOfBirth
    CustomerInput:
      type: object
      properties:
        firstName:
          type: string
          description: Customer's first name
        lastName:
          type: string
          description: Customer's last name
        phoneNumber:
          type: string
          description: Customer's phone number
        postCode:
          type: string
          description: Customer's postal code
        dateOfBirth:
          type: string
          format: date
          description: Customer's date of birth
      required:
        - firstName
        - lastName
        - phoneNumber
        - postCode
        - dateOfBirth